api_article_post_index:
    methods: [GET]
    path: article-post
    controller: ZnBundle\Article\Symfony4\Api\Controllers\ArticleController::index

api_article_post_create:
    methods: [POST]
    path: article-post
    controller: ZnBundle\Article\Symfony4\Api\Controllers\ArticleController::create

api_article_post_view:
    methods: [GET]
    path: article-post/{id}
    controller: ZnBundle\Article\Symfony4\Api\Controllers\ArticleController::view
    requirements:
        id: '\d+'

api_article_post_update:
    methods: [PUT]
    path: article-post/{id}
    controller: ZnBundle\Article\Symfony4\Api\Controllers\ArticleController::update
    requirements:
        id: '\d+'

api_article_post_delete:
    methods: [DELETE]
    path: article-post/{id}
    controller: ZnBundle\Article\Symfony4\Api\Controllers\ArticleController::delete
    requirements:
        id: '\d+'

api_article_post_index_options:
    methods: [OPTIONS]
    path: article-post
    controller: ZnBundle\Article\Symfony4\Api\Controllers\ArticleController::options

api_article_post_options:
    methods: [OPTIONS]
    path: article-post/{id}
    controller: ZnBundle\Article\Symfony4\Api\Controllers\ArticleController::options
    requirements:
        id: '\d+'
